name: Update Contributors

on:
  workflow_dispatch: # Manually trigger the workflow

  schedule:
    - cron: '30 13 1,15 * *' # Run on the 1st and 15th day of each month at 13:30 UTC

jobs:
  update-contributors:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Contributors
        id: contributors
        run: |
          contributors=$(curl -s https://api.github.com/repos/JairTorres1003/JT-Workflows/contributors | jq -r '.[].login')
          echo "contributors=$contributors" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/## Contributors/q' README.md
          echo "## Contributors" >> README.md
          for contributor in ${{ steps.contributors.outputs.contributors }}; do
            avatar_url=$(curl -s https://api.github.com/users/$contributor | jq -r '.avatar_url')
            echo "<a href='https://github.com/$contributor' target='_blank'><img src='data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"40\" height=\"40\" viewBox=\"0 0 40 40\"><circle cx=\"20\" cy=\"20\" r=\"18\" fill=\"#f00\"/></svg>' alt='${contributor}' width='40' height='40'></a>" >> README.md
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update Contributors"
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
