name: Update Contributors

on:
  workflow_dispatch: # Manually trigger the workflow

  schedule:
    - cron: '30 13 1,15 * *' # Run on the 1st and 15th day of each month at 13:30 UTC

jobs:
  update-contributors:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Contributors
        id: contributors
        run: |
          contributors=$(curl -s https://api.github.com/repos/JairTorres1003/JT-Workflows/contributors | jq -c '.')
          echo "CONTRIBUTORS=$contributors" >> "$GITHUB_OUTPUT"

      - name: debug
        env:
          RESPONSE: ${{ steps.contributors.outputs.CONTRIBUTORS }}
        run: |
          echo "$RESPONSE"
