name: Update Contributors

on:
  workflow_dispatch: # Manually trigger the workflow
  schedule:
    - cron: '30 13 1,15 * *' # Run on the 1st and 15th day of each month at 13:30 UTC

jobs:
  update-contributors:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Contributors
        id: contributors
        run: |
          contributors=$(curl -s https://api.github.com/repos/JairTorres1003/JT-Workflows/contributors | jq -c '.')
          echo "CONTRIBUTORS=$contributors" >> "$GITHUB_OUTPUT"

      - name: Update README.md
        id: update-readme
        env:
          RESPONSE: ${{ steps.contributors.outputs.CONTRIBUTORS }}
        run: |
          echo "## Contributors" > README.md.tmp

          for contributor in $(echo $RESPONSE | jq -r '.[] | @base64'); do
            _jq() {
              echo ${contributor} | base64 --decode | jq -r ${1}
            }

            username=$(_jq '.login')
            avatar_url=$(_jq '.avatar_url')

            echo "<a href='https://github.com/$username' target='_blank'><img src='https://images.weserv.nl/?url=$avatar_url&h=100&w=100&mask=circle' alt='$username' title='$username' width='40' height='40' /></a> " >> README.md.tmp
          done

          # Update the content between the specified markers
          awk '/<!-- ALL-CONTRIBUTORS-LIST:START -->/{p=1;print;system("cat README.md.tmp")} /<!-- ALL-CONTRIBUTORS-LIST:END -->/{p=0} !p' README.md > README.updated && mv README.updated README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update Contributors"
          git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
